### ISSUE TITLE
Tags (and APKs) missing?

### ISSUE THREAD

**Issue by IzzySoft** [Sea-n/Android-TG-Bot#11]
According to the build.gradle, there have been several new versions after the last tag was created. Any chance you start tagging again (and attach the APKs to the tags), as you did up to v1.7.0?

**Comment by IzzySoft** [comment]
@Sea-n ^^ any info?

**Comment by Sea-n** [comment]
I think `git log` and `git checkout` is enough

**Comment by IzzySoft** [comment]
Neither of the two create APKs or tags. Not everybody is a developer and/or has a dev environment set up :wink:
