### ISSUE TITLE
989215307635

### ISSUE THREAD

**Issue by takpare** [Sea-n/Android-TG-Bot#6]
مسائل کد 0 درخواست ها را بکشید 0 پالس    
app / src / androidTest / java / taipei / sean / telegram / botplayground /ExampleInstrumentedTest.java

بسته بندی  Taipei.sean.telegram.botplayground ؛

واردات  android.content.Context ؛
واردات  android.support.test.InstrumentationRegistry ؛
واردات  android.support.test.runner.AndroidJUnit4 ؛

وارد کردن  org.junit.Test ؛
وارد  org.junit.runner.RunWith ؛

واردات static  org.junit.Assert.assertEquals ؛

/ * *
 * تست Instrumentation، که بر روی یک دستگاه Android اجرا می شود.
 *
 *see <a href="http://d.android.com/tools/testing"> مستندات تست </a>
 * /
RunWith ( کلاس AndroidJUnit4 . )
 کلاس  عمومی ExampleInstrumentedTest {
    @تست
    استفاده عمومی  void  useAppContext () throws  Exception {
        // متن برنامه تحت آزمایش.
        متن appContext =  InstrumentationRegistry . getTargetContext ()؛

assertEquals         ( " taipei.sean.telegram.botplayground " ، appContext . getPackageName ())
    }
}
 نسخه دسکتاپ

**Comment by Sea-n** [comment]
I will only reply to ENGLISH Issues.
